run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - prealloc
    - unparam

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
  govet:
    enable-all: true

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
